name: countmein
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  email_validator: ^2.0.1
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.6
  firebase_core: ^2.18.0

  
  #Firebase Dependencies
  firebase_core_platform_interface: ^5.0.0
  firebase_analytics: ^10.2.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  firebase_database: ^10.4.0
  photo_view: ^0.14.0
  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_svg: ^1.0.8

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
  - family: NotoSerif
    fonts:
      - asset: assets/fonts/NotoSerif-Regular.ttf
      - asset: assets/fonts/NotoSerif-Bold.ttf
        weight: 700
# fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

